In [2]:
1+1

2

### Python Basic

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5,6])
b = np.array([2,3,4,5,6,7])
c = a+b
print("Addition of two arrays : ", c)

Addition of two arrays :  [ 3  5  7  9 11 13]

## Choose the Right Library:
### PyPDF2: Basic text extraction; doesn't always handle layout well.
### PyMuPDF (fitz): Fast and efficient; works well for text and images.
### pdfplumber: Best for structured data like tables.

In [6]:
from PyPDF2 import PdfReader

# Open the PDF file
reader = PdfReader("E:\Work\OneDrive - Rapifuzz Private Limited\Desktop\Ayush\Data_Science\Python\Ayush Ranjan Soni(CV).pdf")

# Extract text from all pages and one page store a single string value.
for page in reader.pages:
    print(page.extract_text())

<>:4: SyntaxWarning: invalid escape sequence '\W'
<>:4: SyntaxWarning: invalid escape sequence '\W'
C:\Users\AyushRanjanSoni\AppData\Local\Temp\ipykernel_8944\3452780428.py:4: SyntaxWarning: invalid escape sequence '\W'
  reader = PdfReader("E:\Work\OneDrive - Rapifuzz Private Limited\Desktop\Ayush\Data_Science\Python\Ayush Ranjan Soni(CV).pdf")

Ayush Ranjan Soni
Data Analyst
Gurugram, Haryana, India
Phone: 6387063087 | Email: ars7408984015@gmail.com
LinkedIn  | GitHub
Summary
Dynamic Data Analyst with a robust background in data science and computer science. Skilled in transforming raw
data into actionable insights that drive business strategies. Strong p resentation and reporting capabilities.
Experience
         Data Analyst  – RAPIFUZZ Pvt. Ltd. (Present)
• Extract and analyze API data, clean and transform JSON/XML data, and store in Excel for further
analysis.
• Conduct in -depth data analysis and generate co mprehensive reports to support decision -
making.
Data Analyst  – GYPR Pvt. Ltd. (Oct 2023 – Jul 2024)
• Developed and executed assignments in Python, SQL, and statistics for a global student
community.
• Created data visualizations and dashboards using Tableau a nd Power  BI for US -based
universities.
• Collaborated on machine learning projects, enhancing educational content.
Data Analytics Intern  – Mentored Minds (Jul 2023 – Oct 2023)
• Automated data tasks and performed analysis using SQL, Excel, Python, and Tableau.

Education
        Bachelor of Vocation (Software Development & E -Governance)
        National P.G. College, 2020
        Intermediate (12th)
        D.A.V Public School TTPP, 2017
        High School (10th)
        D.A.V Public School TTPP, 2015

Certifications
• Data Science at Relevel by Unacademy (Mar 2022 – Feb 2023)
• Machine Learning with Python Expert at Decodr Technologies (Sep 2020 – Feb 2021)

Key Projects
• Indian Election Analysis : Analyzed Lok Sabha data for voter turnout and party performance using
Excel, MySQL, and Power BI.
• Apartment Price Prediction : Predicted Bangalore flat prices using Linear Regression.
• Border Gavaskar Trophy Analysis : Conducted descriptive analysis of cricket series between India and
Australia.

Skills
• Advanced Excel, SQL, Power BI, Tableau
• Python (Numpy, Pandas, Matplotlib, Sklearn, NLTK etc.)
• Machine Learning, Statistics, Time Series Analysis , NLP

Accomplishments
• Dream11 Data Analyst -SQL Challenge (163rd Rank, 2023)
• SQL Assessment Certification, HackerRank (2023)

In [7]:
# Extract text from all pages and one page store a single string value.
_list = []
for page in reader.pages:
    text = page.extract_text()
    for line in text.splitlines():
        _list.append(line)
print("List of text : ")
print(_list)

List of text :
['Ayush Ranjan Soni  ', 'Data Analyst  ', 'Gurugram, Haryana, India  ', 'Phone: 6387063087 | Email: ars7408984015@gmail.com  ', 'LinkedIn  | GitHub  ', 'Summary  ', 'Dynamic Data Analyst with a robust background in data science and computer science. Skilled in transforming raw ', 'data into actionable insights that drive business strategies. Strong p resentation and reporting capabilities.  ', 'Experience  ', '         Data Analyst  – RAPIFUZZ Pvt. Ltd. (Present)  ', '• Extract and analyze API data, clean and transform JSON/XML data, and store in Excel for further ', 'analysis.  ', '• Conduct in -depth data analysis and generate co mprehensive reports to support decision -', 'making.  ', 'Data Analyst  – GYPR Pvt. Ltd. (Oct 2023 – Jul 2024)  ', '• Developed and executed assignments in Python, SQL, and statistics for a global student ', 'community.  ', '• Created data visualizations and dashboards using Tableau a nd Power  BI for US -based ', 'universities.  ', '• Collaborated on machine learning projects, enhancing educational content.  ', 'Data Analytics Intern  – Mentored Minds (Jul 2023 – Oct 2023)  ', '• Automated data tasks and performed analysis using SQL, Excel, Python, and Tableau.  ', ' ', 'Education  ', '        Bachelor of Vocation (Software Development & E -Governance)  ', '        National P.G. College, 2020  ', '        Intermediate (12th)  ', '        D.A.V Public School TTPP, 2017  ', '        High School (10th)  ', '        D.A.V Public School TTPP, 2015  ', ' ', 'Certifications  ', '• Data Science at Relevel by Unacademy (Mar 2022 – Feb 2023)  ', '• Machine Learning with Python Expert at Decodr Technologies (Sep 2020 – Feb 2021)  ', ' ', 'Key Projects  ', '• Indian Election Analysis : Analyzed Lok Sabha data for voter turnout and party performance using ', 'Excel, MySQL, and Power BI.  ', '• Apartment Price Prediction : Predicted Bangalore flat prices using Linear Regression.  ', '• Border Gavaskar Trophy Analysis : Conducted descriptive analysis of cricket series between India and ', 'Australia.  ', ' ', 'Skills  ', '• Advanced Excel, SQL, Power BI, Tableau  ', '• Python (Numpy, Pandas, Matplotlib, Sklearn, NLTK etc.)  ', '• Machine Learning, Statistics, Time Series Analysis , NLP  ', ' ', 'Accomplishments  ', '• Dream11 Data Analyst -SQL Challenge (163rd Rank, 2023)  ', '• SQL Assessment Certification, HackerRank (2023)  ', ' ', ' ']

In [8]:
len(_list)

52

In [9]:
import fitz  # PyMuPDF

# Open the PDF file
pdf_document = fitz.open("Ayush Ranjan Soni(CV).pdf")

# Extract text from all pages
for page_number in range(len(pdf_document)):
    page = pdf_document[page_number]
    print(page.get_text())

Ayush Ranjan Soni
Data Analyst
Gurugram, Haryana, India
Phone: 6387063087 | Email: ars7408984015@gmail.com
LinkedIn | GitHub
Summary
Dynamic Data Analyst with a robust background in data science and computer science. Skilled in transforming raw
data into actionable insights that drive business strategies. Strong presentation and reporting capabilities.
Experience
         Data Analyst – RAPIFUZZ Pvt. Ltd. (Present)
•
Extract and analyze API data, clean and transform JSON/XML data, and store in Excel for further
analysis.
•
Conduct in-depth data analysis and generate comprehensive reports to support decision-
making.
Data Analyst – GYPR Pvt. Ltd. (Oct 2023 – Jul 2024)
•
Developed and executed assignments in Python, SQL, and statistics for a global student
community.
•
Created data visualizations and dashboards using Tableau and Power BI for US-based
universities.
•
Collaborated on machine learning projects, enhancing educational content.
Data Analytics Intern – Mentored Minds (Jul 2023 – Oct 2023)
•
Automated data tasks and performed analysis using SQL, Excel, Python, and Tableau.

Education
        Bachelor of Vocation (Software Development & E-Governance)
        National P.G. College, 2020
        Intermediate (12th)
        D.A.V Public School TTPP, 2017
        High School (10th)
        D.A.V Public School TTPP, 2015

Certifications
•
Data Science at Relevel by Unacademy (Mar 2022 – Feb 2023)
•
Machine Learning with Python Expert at Decodr Technologies (Sep 2020 – Feb 2021)

Key Projects
•
Indian Election Analysis: Analyzed Lok Sabha data for voter turnout and party performance using
Excel, MySQL, and Power BI.
•
Apartment Price Prediction: Predicted Bangalore flat prices using Linear Regression.
•
Border Gavaskar Trophy Analysis: Conducted descriptive analysis of cricket series between India and
Australia.

Skills
•
Advanced Excel, SQL, Power BI, Tableau
•
Python (Numpy, Pandas, Matplotlib, Sklearn, NLTK etc.)
•
Machine Learning, Statistics, Time Series Analysis, NLP

Accomplishments
•
Dream11 Data Analyst-SQL Challenge (163rd Rank, 2023)
•
SQL Assessment Certification, HackerRank (2023)

In [10]:
import pdfplumber

# Open the PDF file
with pdfplumber.open("Ayush Ranjan Soni(CV).pdf") as pdf:
    for page in pdf.pages:
        print(page.extract_text())

Ayush Ranjan Soni
Data Analyst
Gurugram, Haryana, India
Phone: 6387063087 | Email: ars7408984015@gmail.com
LinkedIn | GitHub
Summary
Dynamic Data Analyst with a robust background in data science and computer science. Skilled in transforming raw
data into actionable insights that drive business strategies. Strong presentation and reporting capabilities.
Experience
Data Analyst – RAPIFUZZ Pvt. Ltd. (Present)
• Extract and analyze API data, clean and transform JSON/XML data, and store in Excel for further
analysis.
• Conduct in-depth data analysis and generate comprehensive reports to support decision-
making.
Data Analyst – GYPR Pvt. Ltd. (Oct 2023 – Jul 2024)
• Developed and executed assignments in Python, SQL, and statistics for a global student
community.
• Created data visualizations and dashboards using Tableau and Power BI for US-based
universities.
• Collaborated on machine learning projects, enhancing educational content.
Data Analytics Intern – Mentored Minds (Jul 2023 – Oct 2023)
• Automated data tasks and performed analysis using SQL, Excel, Python, and Tableau.
Education
Bachelor of Vocation (Software Development & E-Governance)
National P.G. College, 2020
Intermediate (12th)
D.A.V Public School TTPP, 2017
High School (10th)
D.A.V Public School TTPP, 2015
Certifications
• Data Science at Relevel by Unacademy (Mar 2022 – Feb 2023)
• Machine Learning with Python Expert at Decodr Technologies (Sep 2020 – Feb 2021)
Key Projects
• Indian Election Analysis: Analyzed Lok Sabha data for voter turnout and party performance using
Excel, MySQL, and Power BI.
• Apartment Price Prediction: Predicted Bangalore flat prices using Linear Regression.
• Border Gavaskar Trophy Analysis: Conducted descriptive analysis of cricket series between India and
Australia.
Skills
• Advanced Excel, SQL, Power BI, Tableau
• Python (Numpy, Pandas, Matplotlib, Sklearn, NLTK etc.)
• Machine Learning, Statistics, Time Series Analysis, NLP
Accomplishments
• Dream11 Data Analyst-SQL Challenge (163rd Rank, 2023)
• SQL Assessment Certification, HackerRank (2023)

In [11]:
with pdfplumber.open("Ayush Ranjan Soni(CV).pdf") as pdf:
    for page in pdf.pages:
        tables = page.extract_tables()
        for table in tables:
            for row in table:
                print(row)

In [12]:
from PyPDF2 import PdfReader

def find_missing_values(pdf_file, expected_fields):
    missing_values = []  # To store sections with missing data

    # Open the PDF file
    reader = PdfReader(pdf_file)

    # Loop through all pages
    for page_number, page in enumerate(reader.pages, start=1):
        text = page.extract_text()
        if text:  # Ensure the page has text
            for line in text.splitlines():
                # Check for missing fields
                for field in expected_fields:
                    if field in line and (line.strip().endswith(field) or len(line.split(field)[-1].strip()) == 0):
                        missing_values.append(f"Page {page_number}: {line.strip()}")

    return missing_values


# Define the fields to check for
expected_fields = ["Name:", "Age:", "Address:"]

# Call the function
missing_sections = find_missing_values("Ayush Ranjan Soni(CV).pdf", expected_fields)

# Output the result
print("Missing Value Sections:", missing_sections)

Missing Value Sections: []

In [1]:
import pandas as pd
import numpy as np

# Sample data for Task Summary
summary_data = {
    "Task ID": [f"T{str(i+1).zfill(2)}" for i in range(5)],
    "Task Name": [f"Task {i+1}" for i in range(5)],
    "Total Questions": [20] * 5,
    "Correct Answers": [16, 18, 14, 12, 17],
    "Score (%)": [80, 90, 70, 60, 85],
    "Avg. Skill Score": [78, 88, 72, 65, 82],
    "Strengths": ["TCP/IP, WAF", "Wireshark", "Snort", "WAF", "TCP/IP, Wireshark"],
    "Areas to Improve": ["BGP Security", "None", "BGP Security", "Snort", "WAF"]
}
summary_df = pd.DataFrame(summary_data)

# Sample data for Skill Breakdown
skills = ["TCP/IP", "WAF", "Wireshark", "Snort", "BGP Security"]
skill_data = []
for task in summary_data["Task ID"]:
    for skill in skills:
        total_q = np.random.randint(3, 6)
        correct = np.random.randint(0, total_q + 1)
        score = round((correct / total_q) * 100, 2)
        level = "Strong" if score >= 80 else "Moderate" if score >= 50 else "Weak"
        comment = "Well understood" if level == "Strong" else "Needs improvement" if level == "Moderate" else "Needs revision"
        skill_data.append([task, skill, total_q, correct, score, level, comment])
skill_df = pd.DataFrame(skill_data, columns=["Task ID", "Skill Name", "Total Questions", "Correct Answers", "Score (%)", "Level", "Comments"])

# Sample data for Question-Level Detail
question_data = []
for task in summary_data["Task ID"]:
    for skill in skills:
        for q in range(1, 5):  # 4 questions per skill
            correct = np.random.choice([True, False], p=[0.7, 0.3])
            score = 1 if correct else 0
            question_data.append([
                task,
                skill,
                f"Q{q}",
                f"What is a sample question on {skill}?",
                "User Answer",
                "Correct Answer" if correct else "Wrong Answer",
                score,
                f"Explanation for {skill} Q{q}"
            ])
question_df = pd.DataFrame(question_data, columns=["Task ID", "Skill Name", "Question No", "Question Text", "Answer Given", "Correct Answer", "Score", "Explanation"])

# Sample user scorecard
user_df = pd.DataFrame({
    "User ID": ["U001"],
    "Name": ["Ayush"],
    "Total Tasks": [5],
    "Avg Score": [77],
    "Strongest Skill": ["Wireshark"],
    "Weakest Skill": ["Snort"],
    "Overall Rating": ["Good"]
})

# # Write to Excel
# file_path = "/mnt/data/Task_Skill_Report.xlsx"
# with pd.ExcelWriter(file_path, engine='xlsxwriter') as writer:
#     summary_df.to_excel(writer, index=False, sheet_name='Summary Report')
#     skill_df.to_excel(writer, index=False, sheet_name='Skill Breakdown')
#     question_df.to_excel(writer, index=False, sheet_name='Question Detail')
#     user_df.to_excel(writer, index=False, sheet_name='User Score Card')

# file_path

In [2]:
# Re-import necessary libraries after code execution state reset
import pandas as pd
import numpy as np

# Sample data for Task Summary
summary_data = {
    "Task ID": [f"T{str(i+1).zfill(2)}" for i in range(5)],
    "Task Name": [f"Task {i+1}" for i in range(5)],
    "Total Questions": [20] * 5,
    "Correct Answers": [16, 18, 14, 12, 17],
    "Score (%)": [80, 90, 70, 60, 85],
    "Avg. Skill Score": [78, 88, 72, 65, 82],
    "Strengths": ["TCP/IP, WAF", "Wireshark", "Snort", "WAF", "TCP/IP, Wireshark"],
    "Areas to Improve": ["BGP Security", "None", "BGP Security", "Snort", "WAF"]
}
summary_df = pd.DataFrame(summary_data)

# Sample data for Skill Breakdown
skills = ["TCP/IP", "WAF", "Wireshark", "Snort", "BGP Security"]
skill_data = []
for task in summary_data["Task ID"]:
    for skill in skills:
        total_q = np.random.randint(3, 6)
        correct = np.random.randint(0, total_q + 1)
        score = round((correct / total_q) * 100, 2)
        level = "Strong" if score >= 80 else "Moderate" if score >= 50 else "Weak"
        comment = "Well understood" if level == "Strong" else "Needs improvement" if level == "Moderate" else "Needs revision"
        skill_data.append([task, skill, total_q, correct, score, level, comment])
skill_df = pd.DataFrame(skill_data, columns=["Task ID", "Skill Name", "Total Questions", "Correct Answers", "Score (%)", "Level", "Comments"])

# Sample data for Question-Level Detail
question_data = []
for task in summary_data["Task ID"]:
    for skill in skills:
        for q in range(1, 5):  # 4 questions per skill
            correct = np.random.choice([True, False], p=[0.7, 0.3])
            score = 1 if correct else 0
            question_data.append([
                task,
                skill,
                f"Q{q}",
                f"What is a sample question on {skill}?",
                "User Answer",
                "Correct Answer" if correct else "Wrong Answer",
                score,
                f"Explanation for {skill} Q{q}"
            ])
question_df = pd.DataFrame(question_data, columns=["Task ID", "Skill Name", "Question No", "Question Text", "Answer Given", "Correct Answer", "Score", "Explanation"])

# Sample user scorecard
user_df = pd.DataFrame({
    "User ID": ["U001"],
    "Name": ["Ayush"],
    "Total Tasks": [5],
    "Avg Score": [77],
    "Strongest Skill": ["Wireshark"],
    "Weakest Skill": ["Snort"],
    "Overall Rating": ["Good"]
})

# Write to Excel
# file_path = "/mnt/data/Task_Skill_Report.xlsx"
# with pd.ExcelWriter(file_path, engine='xlsxwriter') as writer:
#     summary_df.to_excel(writer, index=False, sheet_name='Summary Report')
#     skill_df.to_excel(writer, index=False, sheet_name='Skill Breakdown')
#     question_df.to_excel(writer, index=False, sheet_name='Question Detail')
#     user_df.to_excel(writer, index=False, sheet_name='User Score Card')

# file_path

In [3]:
summary_df

,Task ID,Task Name,Total Questions,Correct Answers,Score (%),Avg. Skill Score,Strengths,Areas to Improve
0,T01,Task 1,20,16,80,78,"TCP/IP, WAF",BGP Security
1,T02,Task 2,20,18,90,88,Wireshark,None
2,T03,Task 3,20,14,70,72,Snort,BGP Security
3,T04,Task 4,20,12,60,65,WAF,Snort
4,T05,Task 5,20,17,85,82,"TCP/IP, Wireshark",WAF

In [4]:
skill_df

,Task ID,Skill Name,Total Questions,Correct Answers,Score (%),Level,Comments
0,T01,TCP/IP,5,0,0.00,Weak,Needs revision
1,T01,WAF,3,2,66.67,Moderate,Needs improvement
2,T01,Wireshark,3,3,100.00,Strong,Well understood
3,T01,Snort,3,1,33.33,Weak,Needs revision
4,T01,BGP Security,4,3,75.00,Moderate,Needs improvement
5,T02,TCP/IP,3,1,33.33,Weak,Needs revision
6,T02,WAF,3,0,0.00,Weak,Needs revision
7,T02,Wireshark,5,0,0.00,Weak,Needs revision
8,T02,Snort,4,3,75.00,Moderate,Needs improvement
9,T02,BGP Security,4,3,75.00,Moderate,Needs improvement
10,T03,TCP/IP,3,0,0.00,Weak,Needs revision
11,T03,WAF,3,0,0.00,Weak,Needs revision
12,T03,Wireshark,5,0,0.00,Weak,Needs revision
13,T03,Snort,5,5,100.00,Strong,Well understood
14,T03,BGP Security,5,1,20.00,Weak,Needs revision
15,T04,TCP/IP,4,0,0.00,Weak,Needs revision
16,T04,WAF,5,3,60.00,Moderate,Needs improvement
17,T04,Wireshark,4,4,100.00,Strong,Well understood
18,T04,Snort,5,1,20.00,Weak,Needs revision
19,T04,BGP Security,3,1,33.33,Weak,Needs revision
20,T05,TCP/IP,5,4,80.00,Strong,Well understood
21,T05,WAF,4,0,0.00,Weak,Needs revision
22,T05,Wireshark,3,1,33.33,Weak,Needs revision
23,T05,Snort,3,1,33.33,Weak,Needs revision
24,T05,BGP Security,4,0,0.00,Weak,Needs revision

In [5]:
question_df

,Task ID,Skill Name,Question No,Question Text,Answer Given,Correct Answer,Score,Explanation
0,T01,TCP/IP,Q1,What is a sample question on TCP/IP?,User Answer,Wrong Answer,0,Explanation for TCP/IP Q1
1,T01,TCP/IP,Q2,What is a sample question on TCP/IP?,User Answer,Wrong Answer,0,Explanation for TCP/IP Q2
2,T01,TCP/IP,Q3,What is a sample question on TCP/IP?,User Answer,Correct Answer,1,Explanation for TCP/IP Q3
3,T01,TCP/IP,Q4,What is a sample question on TCP/IP?,User Answer,Correct Answer,1,Explanation for TCP/IP Q4
4,T01,WAF,Q1,What is a sample question on WAF?,User Answer,Wrong Answer,0,Explanation for WAF Q1
...,...,...,...,...,...,...,...,...
95,T05,Snort,Q4,What is a sample question on Snort?,User Answer,Wrong Answer,0,Explanation for Snort Q4
96,T05,BGP Security,Q1,What is a sample question on BGP Security?,User Answer,Correct Answer,1,Explanation for BGP Security Q1
97,T05,BGP Security,Q2,What is a sample question on BGP Security?,User Answer,Correct Answer,1,Explanation for BGP Security Q2
98,T05,BGP Security,Q3,What is a sample question on BGP Security?,User Answer,Correct Answer,1,Explanation for BGP Security Q3
99,T05,BGP Security,Q4,What is a sample question on BGP Security?,User Answer,Wrong Answer,0,Explanation for BGP Security Q4

In [6]:
user_df

,User ID,Name,Total Tasks,Avg Score,Strongest Skill,Weakest Skill,Overall Rating
0,U001,Ayush,5,77,Wireshark,Snort,Good

In [6]:
import math

physics = [15, 12, 8, 8, 7, 7, 7, 6, 5, 3]
history = [10, 25, 17, 11, 13, 17, 20, 13, 9, 15]

def calculate_Pearson_Correlation(x, y):
    n = len(x)
    if n != len(y):
        raise ValueError("Lists must have the same length")

    mean_x = sum(x) / n
    mean_y = sum(y) / n
    xi_mean_x = [xi - mean_x for xi in x]
    yi_mean_y = [yi - mean_y for yi in y]
    sum_xy = sum(xi * yi for xi, yi in zip(xi_mean_x, yi_mean_y))
    numerator = sum_xy

    xi_mean_x2 = [xi ** 2 for xi in xi_mean_x]
    yi_mean_y2 = [yi ** 2 for yi in yi_mean_y]
    sum_x2 = sum(xi_mean_x2)
    sum_y2 = sum(yi_mean_y2)
    denominator = math.sqrt(sum_x2 * sum_y2)

    if denominator == 0:
        return 0

    return numerator / denominator

In [7]:
r = calculate_Pearson_Correlation(physics, history)
print(f"Pearson correlation coefficient: {r:.3f}")

Pearson correlation coefficient: 0.145